# Generated by Django 6.0.3 on 2026-04-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_book_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookimage',
            name='img',
        ),
        migrations.AddField(
            model_name='bookimage',
            name='addit_imgs',
            field=models.ImageField(default='', upload_to='book_images'),
            preserve_default=False,
        ),
    ]
