# Generated by Django 6.0.3 on 2026-04-11 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_bookimage_img_bookimage_addit_imgs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookImage',
            new_name='BookImages',
        ),
    ]
