# Generated by Django 6.0.3 on 2026-04-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_genre_book_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre_name',
            field=models.CharField(choices=[('available', 'историческое'), ('available', 'роман'), ('available', 'детектив'), ('available', 'приключения'), ('available', 'проза')], max_length=100),
        ),
    ]
