# Generated by Django 6.0.3 on 2026-04-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_genre_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre_name',
            field=models.CharField(choices=[('historical', 'историческое'), ('romance', 'роман'), ('detective', 'детектив'), ('adventure', 'приключения'), ('prose', 'проза')], max_length=100),
        ),
    ]
