# Generated by Django 6.0.3 on 2026-04-29 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_book_genres'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('aviable', 'доступна'), ('rented', 'нет свободных экземпляров'), ('unaviable', 'недоступна')], max_length=100)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.book')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('planned_return_date', models.DateField()),
                ('total_price', models.FloatField()),
                ('return_status', models.BooleanField(default=False)),
                ('price_per_day', models.FloatField()),
                ('book_copy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.bookcopy')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Rental',
        ),
    ]
