# Generated by Django 6.0.3 on 2026-04-29 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_bookcopy_rent_delete_rental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcopy',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='copies', to='main.book'),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='status',
            field=models.CharField(choices=[('available', 'доступна'), ('rented', 'нет свободных экземпляров'), ('unavailable', 'недоступна')], max_length=100),
        ),
    ]
