# Generated by Django 6.0.3 on 2026-05-01 12:32

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_bookcopy_book_alter_bookcopy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='planned_return_date',
            field=models.DateField(default=main.models.default_time),
        ),
    ]
