# Generated by Django 6.0.3 on 2026-05-01 14:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_rent_planned_return_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='book_copy',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='price_per_day',
        ),
        migrations.AlterField(
            model_name='rent',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rent',
            name='total_price',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='RentBookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_day', models.FloatField()),
                ('book_copy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.bookcopy')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.rent')),
            ],
        ),
    ]
