# Generated by Django 6.0.3 on 2026-05-01 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_rent_book_copy_remove_rent_price_per_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField(auto_now_add=True)),
                ('penalty', models.FloatField(default=0)),
                ('total_price', models.FloatField(default=0)),
                ('rental', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.rent')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage', models.TextField(blank=True, null=True)),
                ('fine', models.FloatField(default=0)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('book_copy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.bookcopy')),
                ('return_act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.return')),
            ],
        ),
    ]
