# Generated by Django 6.0.3 on 2026-05-02 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_return_returnitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returnitem',
            old_name='fine',
            new_name='pen',
        ),
    ]
